name: carbuddy
description: "An AI-powered microsleep detection system for safer driving"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  lottie: ^2.7.0
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/